Husst 3.01 Husst4MaaS Änderungen
HUSST-de/HUSST pull request #29
Opened 2021-08-03 16:45 UTC by AMCON-Gerst

Relevante Änderungen sind in diesem (zweiten) Commit zu finden: https://github.com/HUSST-de/HUSST/commit/8bf51edfa97af64443a0bb498d5c7aa11fa05b4e

Der erste Commit ist die Kopie der Husst 3.00 und Umbenennung in Husst 3.01.
Der dritte Commit ist ein Reformat des Dokuments, in dem alle Leerzeichen und Tab Einrückungen Vereinheitlicht wurden und einige manuelle Umbrüche in der Doku optimiert wurden. Inhaltlich hat sich in diesem Commit nichts geändert.

ToDos:
- [ ] @horst-p-w-neubauer XSL und Abbildung SQLite ergänzen.

2021-08-04 12:42 UTC, ICA-uw approved these changes
Sieht sehr gut aus,

2021-08-04 14:49 UTC, highQ-Gumbert approved these changes

2021-08-04 14:49 UTC, highQ-Gumbert approved these changes

2021-08-04 14:50 UTC, highQ-Gumbert approved these changes

2021-08-30 09:06 UTC, AMCON-Gerst commented
Vorschlag für einen Changelog: https://github.com/HUSST-de/HUSST/blob/Husst_3-01_Husst4Maas/Version%203/README.md

2021-09-01 05:55 UTC, ICA-uw approved these changes

2021-09-01 05:56 UTC, ICA-uw approved these changes

2021-09-01 15:29 UTC, highQ-Gumbert approved these changes

2021-09-01 15:29 UTC, highQ-Gumbert approved these changes

2021-09-09 18:53 UTC, horst-p-w-neubauer commented
Ich habe noch für vier Husst-Typen Standard-Definitionen hinterlegt, bitte schaut euch die noch mal an ob ihr die so bestätigen könnt:
Husst-Standard-ID-Definitonen ergänzt
  - ID_OTPTypHUSST_Type
  - ID_PreisquelleHUSST_Type
  - ID_SortengruppentypHUSST_Type
  - ID_SortenklasseHUSST_Type

2021-09-09 18:59 UTC, horst-p-w-neubauer commented
Außerdem noch einen Verweis in Tarifrelevantepunkte korrigiert (hoffe ich).

2021-09-09 19:17 UTC, horst-p-w-neubauer requested changes
Für die Husst4Maas Umsetzung fehlt noch die Definition von Zahlarten (da steht noch ein ToDo für @AMCON-Gerst ).

2021-09-10 07:54 UTC, AMCON-Gerst commented
> Für die Husst4Maas Umsetzung fehlt noch die Definition von Zahlarten

Die fehlt, weil auf meine Anfrage wie Kleingranular das erfolgen soll damals keine Antwort kam :)
Ich würde folgende Werte vorschlagen: 
- Bar
- Kartenzahlung (Giro, Kredit etc., alles was das angeschlossenes Terminal kann)
- KA-Zahlung
- Rechnung

2021-09-10 08:09 UTC, AMCON-Gerst commented
**Zu den OTP-Typen:**
Mir haben bisher immer 10 und 20 gereicht. Hat sonst (außer Krauth) jemand einen Bedarf an diesem OTP-Typen? Wenn nicht, würde ich diese nicht im Husst Standard sondern in den eigenen Bereich ab 1000 sehen.

**Zu den Sortenklassen:**
(Ich weiß, dass die Sortenklasse so in Husst 2 inkl. 2 Krauth Ergänzungen definiert ist)
Die Werte 1-19 sind jetzt eine Zusammensetzung aus dem Sortenttyp und der Preisfindung. Ist das sinnführend? Auch die anderen Werte sind über als Sortentyp verfügbar oder fehlen dort, gehören aber dort mit rein. Wofür wollen wir die Sortenklasse in Husst 3 nutzen?
Zudem ist es zwar schön die Krauth Standardwerte für Fehleinnahme und Restgeldquittung zu haben, aber ich kann niemanden erklären, warum nach 20 die 97 und dann die 103 kommt. Evtl. sollten wir hier in Husst 3 einen Umbruch wagen und vernünftige Werte nehmen (30 und 40 oder 21 und 22 o.ä.)

2021-09-10 08:55 UTC, ICA-uw commented
> **Zu den OTP-Typen:**
> Mir haben bisher immer 10 und 20 gereicht. Hat sonst (außer Krauth) jemand einen Bedarf an diesem OTP-Typen? Wenn nicht, würde ich diese nicht im Husst Standard sondern in den eigenen Bereich ab 1000 sehen.
> 
> **Zu den Sortenklassen:**
> (Ich weiß, dass die Sortenklasse so in Husst 2 inkl. 2 Krauth Ergänzungen definiert ist)
> Die Werte 1-19 sind jetzt eine Zusammensetzung aus dem Sortenttyp und der Preisfindung. Ist das sinnführend? Auch die anderen Werte sind über als Sortentyp verfügbar oder fehlen dort, gehören aber dort mit rein. Wofür wollen wir die Sortenklasse in Husst 3 nutzen?
> Zudem ist es zwar schön die Krauth Standardwerte für Fehleinnahme und Restgeldquittung zu haben, aber ich kann niemanden erklären, warum nach 20 die 97 und dann die 103 kommt. Evtl. sollten wir hier in Husst 3 einen Umbruch wagen und vernünftige Werte nehmen (30 und 40 oder 21 und 22 o.ä.)
> 
> **Zu den Sortengruppentyp:**
> Wer erklärt mir, warum es 1, 2, 10 und 101 gibt? Warum nicht 1, 2, 3, 4 oder 1, 2, 10, 20 weil 1 und 2 schon noch zusammengehören. Oder dann besser 1, 2, 11, 21 oder so? Mit 1, 2, 10, 101 wirkt undurchdacht und zusammengewürfelt.
> Brauchen wir noch Sortengruppentypen für die Husst4Maas Anwendungsfälle?
> Braucht jmd. außer Krauth den Wert 2? Sonst wäre das wie bei den OTP-Typen für mich ein Wert, der in den 1000er Bereich gehört.

Zu den OTP-Typen
Wir haben in einem Projekt noch den OTP-Typ 30 definiert für ein spezielles Fahrtzielverzeichnis.
Ich denke aber, dass man diese Werte generell in der Tabelle DefOTPTypen Projekt spezifisch definieren sollte.

Zu den Sortenklassen
Ich hatte da ja mal nach dem Unterschied zwischen Sortenklassen und Sortentypen gefragt. Sie scheinen mir gleich.
Diese können vorgegeben werden für die Standardfälle. Spezialfälle sollten dann auch Projekt spezifisch in den Def-Tabellen definiert werden.

Sortengruppen?
Keine Ahnung. Haben wir so verwendet wir vorgefunden ;-)

2021-09-10 12:20 UTC, horst-p-w-neubauer commented
Ich habe den Eindruck, wir brauchen einen Diskussions- und Beschlusstermin für die offenen Fragen zu den Standardwerten. Deshalb schlage ich vor, dass wir den Termin am 22. September, 15:30-16:30 dazu nutzen. Ggf. sollten wir uns nach hinten raus noch ein paar Minuten Zeit reservieren, 1h könnte etwas kurz sein, für die vielen verschiedenen Aspekte. Vielleicht kann der AP 2 Leiter auch den Termin auf 1,5 oder 2h verlängern.

2021-09-13 10:05 UTC, AMCON-Gerst commented
Hätte wer etwas dagegen den Sortentyp Überzahlung mit Aufzunehmen? Der fehlt anscheinend noch

2021-09-14 13:32 UTC, AMCON-Gerst commented
Überlegungen für den Termin am 22.09.:
- Definition von Wertebereichen in den freien Teilen von Enumerationen

2021-09-17 06:38 UTC, ICA-uw approved these changes

2022-01-26 23:21 UTC, horst-p-w-neubauer approved these changes

2022-01-27 09:19 UTC, merged